use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Clone, Debug, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Project {
    pub id: String,
    pub name: String,
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct TaskSummary {
    pub key: String,
    pub title: String,
    pub status: String,
    pub relative_dir: String,
    pub parent_key: Option<String>,
    pub child_keys: Vec<String>,
    pub archived: bool,
    pub revision: String,
}

#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Snapshot {
    pub project_id: String,
    pub epoch: String,
    #[ts(type = "number")]
    pub revision: u64,
    pub tasks: Vec<TaskSummary>,
    pub root_keys: Vec<String>,
    pub scan_ms: f64,
    pub diagnostics: Vec<String>,
}

#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Changes {
    pub project_id: String,
    pub epoch: String,
    #[ts(type = "number")]
    pub base_revision: u64,
    #[ts(type = "number")]
    pub revision: u64,
    pub reset_required: bool,
    pub upserts: Vec<TaskSummary>,
    pub removed: Vec<String>,
    pub root_keys: Option<Vec<String>>,
    pub document_task_keys: Vec<String>,
    pub diagnostics: Vec<String>,
}

#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct DocEntry {
    pub key: String,
    pub path: String,
    pub name: String,
}

#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Document {
    pub task_key: String,
    pub key: String,
    pub content: String,
    pub revision: String,
    pub read_ms: f64,
}

#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Bootstrap {
    pub epoch: String,
    pub projects: Vec<Project>,
    pub auto_benchmark: bool,
    pub auto_benchmark_repeats: u32,
    pub auto_benchmark_seconds: u32,
}

#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct Invalidated {
    pub project_id: String,
    pub epoch: String,
    #[ts(type = "number")]
    pub revision: u64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct PlannerSettings {
    #[ts(type = "Record<string, string>")]
    pub project_colors: std::collections::BTreeMap<String, String>,
    pub schedules: Vec<ScheduleEntry>,
}

#[derive(Clone, Debug, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ScheduleEntry {
    pub id: String,
    pub project_id: String,
    pub task_key: String,
    pub title: String,
    pub start_date: String,
    pub end_date: String,
}

#[derive(Clone, Debug, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ScheduleUpdate {
    pub id: Option<String>,
    pub project_id: String,
    pub task_key: String,
    pub start_date: Option<String>,
    pub end_date: Option<String>,
}

#[derive(Clone, Debug, Serialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct CalendarProject {
    pub project_id: String,
    pub tasks: Vec<TaskSummary>,
    pub diagnostics: Vec<String>,
}

pub fn typescript() -> String {
    let declarations = [
        Project::decl(),
        TaskSummary::decl(),
        Snapshot::decl(),
        Changes::decl(),
        DocEntry::decl(),
        Document::decl(),
        Bootstrap::decl(),
        Invalidated::decl(),
        PlannerSettings::decl(),
        ScheduleEntry::decl(),
        ScheduleUpdate::decl(),
        CalendarProject::decl(),
    ];
    format!(
        "// Generated by cargo run --bin export-contracts. Do not edit.\n{}\n",
        declarations.map(|s| format!("export {s}")).join("\n\n")
    )
}
